# action.yml
name: 'Close Milestone With Tagging'
description: 'Close a GitHub milestone while tagging with the same name'
author: 'Adler Hsieh'
branding:
  icon: 'tag' 
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
