# action.yml
name: 'Prepare Release'
description: 'Prepare the repository for the next release'
author: 'Adler Hsieh'
branding:
  icon: 'git-branch' 
  color: 'green'
# inputs:
#   :  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
